### ISSUE TITLE
[Bug] Activation Mode "Hover over all selections" opens in a sub-menu rather than main Pie Menu

### ISSUE THREAD

**Issue by Sineval** [dumbeau/AutoHotPie#61]
Found this when I played with Steam Controller and tried to configure it's Desktop Config to use Auto Hot Pie (another case of up/down key event detection issues, forcing me away from "Hover over submenus, release on function" Activation Mode).

When opening Pie Menu configured like below:

![image](https://user-images.githubusercontent.com/38625241/179388926-8a07a44c-0362-4081-aa7e-71d13d6d1885.png)

The menu always opens in "Keyboard Shortcuts" sub-menu. It looks like the first highlighted slice is being activated on start.

Context:
OS: Windows 10 Version 10.0.19044 Build 19044
Auto Hot Pie version: 1.0.21-alpha

**Comment by dumbeau** [comment]
Fixed in v1.0.22 and hotfixed in v1.0.21.  This fix will need to be cleaned up for the next version, but it is functional again.

**Comment by Sineval** [comment]
This is fixed in hotfixed 1.0.21, but still present in 1.0.22.
 FYI @dumbeau

**Comment by dumbeau** [comment]
Huh, they should be essentially the same and I tested both of them.  I just reuploaded just in case, could you try redownloading 1.0.22 and trying it again?

**Comment by Sineval** [comment]
Ok, redownloaded 1.0.22 back, and now it works correctly.

Interesting, I have updated not fixed 1.0.21 to 1.0.22 where it didn't work. Then downgraded to 1.0.21 hotfix and finally updated back to 1.0.22. Looks like files didn't update correctly the first time I did the update.

**Comment by dumbeau** [comment]
There might be an issue with the installer verifying that install files are not being used when it installs.  I can look into that.
